### ISSUE TITLE
Please make your apps more accessible

### ISSUE THREAD

**Issue by cjoshmartin** [BboyAkers/ReactApp#1]
Its hard for people, especially people that are not developers to look at your content.

I found a link that can help you easily put your react app on github pages, that way it is easy for everyone (including yourself) to access/publish your work.

https://medium.freecodecamp.org/surge-vs-github-pages-deploying-a-create-react-app-project-c0ecbf317089

**Comment by BboyAkers** [comment]
That's not the point of this application, I'm just using this repo to play and freshen up my React skills.
